### ISSUE TITLE
cannot pickle 'generator' object

### ISSUE THREAD

**Issue by barrycarey** [SthPhoenix/InsightFace-REST#135]
I'm running into an odd issue.  Everything runs fine on my Ubuntu 22.04 desktop.  However, when running on Ubuntu Server 22.04 it appears to blow up when trying to perform some caching. 

Same issue with Docker and without.  Also tested multiple driver versions. 

I'm hoping you can provide some insight 

```
ifr-trt-gpu0-1  | Traceback (most recent call last):
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/core/caching.py", line 469, in save
ifr-trt-gpu0-1  |     data_name = overloads[key]
ifr-trt-gpu0-1  | KeyError: ((Function(<function mean at 0x7f2ae8080700>), Literal[int](0), Array(float32, 2, 'C', True, aligned=True)), ('x86_64-unknown-linux-gnu', 'znver2', '+64bit,+adx,+aes,-amx-bf16,-amx-int8,-amx-tile,+avx,+avx2,-avx512bf16,-avx512bitalg,-avx512bw,-avx512cd,-avx512dq,-avx512er,-avx512f,-avx512fp16,-avx512ifma,-avx512pf,-avx512vbmi,-avx512vbmi2,-avx512vl,-avx512vnni,-avx512vp2intersect,-avx512vpopcntdq,-avxvnni,+bmi,+bmi2,-cldemote,+clflushopt,+clwb,+clzero,+cmov,+crc32,+cx16,+cx8,-enqcmd,+f16c,+fma,-fma4,+fsgsbase,+fxsr,-gfni,-hreset,-invpcid,-kl,-lwp,+lzcnt,+mmx,+movbe,-movdir64b,-movdiri,-mwaitx,+pclmul,-pconfig,-pku,+popcnt,-prefetchwt1,+prfchw,-ptwrite,-rdpid,+rdrnd,+rdseed,-rtm,+sahf,-serialize,-sgx,+sha,-shstk,+sse,+sse2,+sse3,+sse4.1,+sse4.2,+sse4a,+ssse3,-tbm,-tsxldtrk,-uintr,-vaes,-vpclmulqdq,-waitpkg,-wbnoinvd,-widekl,-xop,+xsave,+xsavec,+xsaveopt,+xsaves'), ('82cae006504de9480622b3b666eff5717831cdac00ab1797a5faf5336c258f35', 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855'))
ifr-trt-gpu0-1  | 
ifr-trt-gpu0-1  | During handling of the above exception, another exception occurred:
ifr-trt-gpu0-1  | 
ifr-trt-gpu0-1  | Traceback (most recent call last):
ifr-trt-gpu0-1  |   File "/app/api_trt/app.py", line 98, in extract
ifr-trt-gpu0-1  |     output = await processing.extract(images, max_size=data.max_size, return_face_data=data.return_face_data,
ifr-trt-gpu0-1  |   File "/app/api_trt/modules/processing.py", line 135, in extract
ifr-trt-gpu0-1  |     output = await self.model.embed(images,
ifr-trt-gpu0-1  |   File "/app/api_trt/modules/face_model.py", line 546, in embed
ifr-trt-gpu0-1  |     faces_by_img = (e for e in await _get([img for img in imgs_iterable]))
ifr-trt-gpu0-1  |   File "/app/api_trt/modules/face_model.py", line 401, in get
ifr-trt-gpu0-1  |     crops = face_align.norm_crop_batched(images[orig_id], landmarks)
ifr-trt-gpu0-1  |   File "/app/api_trt/modules/utils/fast_face_align.py", line 237, in norm_crop_batched
ifr-trt-gpu0-1  |     Ms = estimate_norm_batch(landmarks, image_size, mode)
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/core/dispatcher.py", line 442, in _compile_for_args
ifr-trt-gpu0-1  |     raise e
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/core/dispatcher.py", line 375, in _compile_for_args
ifr-trt-gpu0-1  |     return_val = self.compile(tuple(argtypes))
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/core/dispatcher.py", line 905, in compile
ifr-trt-gpu0-1  |     cres = self._compiler.compile(args, return_type)
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/core/dispatcher.py", line 80, in compile
ifr-trt-gpu0-1  |     status, retval = self._compile_cached(args, return_type)
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/core/dispatcher.py", line 94, in _compile_cached
ifr-trt-gpu0-1  |     retval = self._compile_core(args, return_type)
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/core/dispatcher.py", line 107, in _compile_core
ifr-trt-gpu0-1  |     cres = compiler.compile_extra(self.targetdescr.typing_context,
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/core/compiler.py", line 744, in compile_extra
ifr-trt-gpu0-1  |     return pipeline.compile_extra(func)
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/core/compiler.py", line 438, in compile_extra
ifr-trt-gpu0-1  |     return self._compile_bytecode()
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/core/compiler.py", line 506, in _compile_bytecode
ifr-trt-gpu0-1  |     return self._compile_core()
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/core/compiler.py", line 481, in _compile_core
ifr-trt-gpu0-1  |     raise e
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/core/compiler.py", line 472, in _compile_core
ifr-trt-gpu0-1  |     pm.run(self.state)
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/core/compiler_machinery.py", line 364, in run
ifr-trt-gpu0-1  |     raise e
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/core/compiler_machinery.py", line 356, in run
ifr-trt-gpu0-1  |     self._runPass(idx, pass_inst, state)
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/core/compiler_lock.py", line 35, in _acquire_compile_lock
ifr-trt-gpu0-1  |     return func(*args, **kwargs)
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/core/compiler_machinery.py", line 311, in _runPass
ifr-trt-gpu0-1  |     mutated |= check(pss.run_pass, internal_state)
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/core/compiler_machinery.py", line 273, in check
ifr-trt-gpu0-1  |     mangled = func(compiler_state)
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/core/typed_passes.py", line 112, in run_pass
ifr-trt-gpu0-1  |     typemap, return_type, calltypes, errs = type_inference_stage(
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/core/typed_passes.py", line 93, in type_inference_stage
ifr-trt-gpu0-1  |     errs = infer.propagate(raise_errors=raise_errors)
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/core/typeinfer.py", line 1083, in propagate
ifr-trt-gpu0-1  |     errors = self.constraints.propagate(self)
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/core/typeinfer.py", line 182, in propagate
ifr-trt-gpu0-1  |     raise e
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/core/typeinfer.py", line 160, in propagate
ifr-trt-gpu0-1  |     constraint(typeinfer)
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/core/typeinfer.py", line 583, in __call__
ifr-trt-gpu0-1  |     self.resolve(typeinfer, typevars, fnty)
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/core/typeinfer.py", line 606, in resolve
ifr-trt-gpu0-1  |     sig = typeinfer.resolve_call(fnty, pos_args, kw_args)
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/core/typeinfer.py", line 1577, in resolve_call
ifr-trt-gpu0-1  |     return self.context.resolve_function_type(fnty, pos_args, kw_args)
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/core/typing/context.py", line 196, in resolve_function_type
ifr-trt-gpu0-1  |     res = self._resolve_user_function_type(func, args, kws)
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/core/typing/context.py", line 248, in _resolve_user_function_type
ifr-trt-gpu0-1  |     return func.get_call_type(self, args, kws)
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/core/types/functions.py", line 541, in get_call_type
ifr-trt-gpu0-1  |     self.dispatcher.get_call_template(args, kws)
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/core/dispatcher.py", line 318, in get_call_template
ifr-trt-gpu0-1  |     self.compile(tuple(args))
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/core/dispatcher.py", line 905, in compile
ifr-trt-gpu0-1  |     cres = self._compiler.compile(args, return_type)
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/core/dispatcher.py", line 80, in compile
ifr-trt-gpu0-1  |     status, retval = self._compile_cached(args, return_type)
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/core/dispatcher.py", line 94, in _compile_cached
ifr-trt-gpu0-1  |     retval = self._compile_core(args, return_type)
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/core/dispatcher.py", line 107, in _compile_core
ifr-trt-gpu0-1  |     cres = compiler.compile_extra(self.targetdescr.typing_context,
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/core/compiler.py", line 744, in compile_extra
ifr-trt-gpu0-1  |     return pipeline.compile_extra(func)
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/core/compiler.py", line 438, in compile_extra
ifr-trt-gpu0-1  |     return self._compile_bytecode()
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/core/compiler.py", line 506, in _compile_bytecode
ifr-trt-gpu0-1  |     return self._compile_core()
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/core/compiler.py", line 481, in _compile_core
ifr-trt-gpu0-1  |     raise e
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/core/compiler.py", line 472, in _compile_core
ifr-trt-gpu0-1  |     pm.run(self.state)
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/core/compiler_machinery.py", line 364, in run
ifr-trt-gpu0-1  |     raise e
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/core/compiler_machinery.py", line 356, in run
ifr-trt-gpu0-1  |     self._runPass(idx, pass_inst, state)
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/core/compiler_lock.py", line 35, in _acquire_compile_lock
ifr-trt-gpu0-1  |     return func(*args, **kwargs)
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/core/compiler_machinery.py", line 311, in _runPass
ifr-trt-gpu0-1  |     mutated |= check(pss.run_pass, internal_state)
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/core/compiler_machinery.py", line 273, in check
ifr-trt-gpu0-1  |     mangled = func(compiler_state)
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/core/typed_passes.py", line 112, in run_pass
ifr-trt-gpu0-1  |     typemap, return_type, calltypes, errs = type_inference_stage(
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/core/typed_passes.py", line 93, in type_inference_stage
ifr-trt-gpu0-1  |     errs = infer.propagate(raise_errors=raise_errors)
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/core/typeinfer.py", line 1083, in propagate
ifr-trt-gpu0-1  |     errors = self.constraints.propagate(self)
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/core/typeinfer.py", line 182, in propagate
ifr-trt-gpu0-1  |     raise e
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/core/typeinfer.py", line 160, in propagate
ifr-trt-gpu0-1  |     constraint(typeinfer)
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/core/typeinfer.py", line 583, in __call__
ifr-trt-gpu0-1  |     self.resolve(typeinfer, typevars, fnty)
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/core/typeinfer.py", line 606, in resolve
ifr-trt-gpu0-1  |     sig = typeinfer.resolve_call(fnty, pos_args, kw_args)
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/core/typeinfer.py", line 1577, in resolve_call
ifr-trt-gpu0-1  |     return self.context.resolve_function_type(fnty, pos_args, kw_args)
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/core/typing/context.py", line 196, in resolve_function_type
ifr-trt-gpu0-1  |     res = self._resolve_user_function_type(func, args, kws)
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/core/typing/context.py", line 248, in _resolve_user_function_type
ifr-trt-gpu0-1  |     return func.get_call_type(self, args, kws)
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/core/types/functions.py", line 541, in get_call_type
ifr-trt-gpu0-1  |     self.dispatcher.get_call_template(args, kws)
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/core/dispatcher.py", line 318, in get_call_template
ifr-trt-gpu0-1  |     self.compile(tuple(args))
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/core/dispatcher.py", line 905, in compile
ifr-trt-gpu0-1  |     cres = self._compiler.compile(args, return_type)
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/core/dispatcher.py", line 80, in compile
ifr-trt-gpu0-1  |     status, retval = self._compile_cached(args, return_type)
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/core/dispatcher.py", line 94, in _compile_cached
ifr-trt-gpu0-1  |     retval = self._compile_core(args, return_type)
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/core/dispatcher.py", line 107, in _compile_core
ifr-trt-gpu0-1  |     cres = compiler.compile_extra(self.targetdescr.typing_context,
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/core/compiler.py", line 744, in compile_extra
ifr-trt-gpu0-1  |     return pipeline.compile_extra(func)
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/core/compiler.py", line 438, in compile_extra
ifr-trt-gpu0-1  |     return self._compile_bytecode()
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/core/compiler.py", line 506, in _compile_bytecode
ifr-trt-gpu0-1  |     return self._compile_core()
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/core/compiler.py", line 481, in _compile_core
ifr-trt-gpu0-1  |     raise e
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/core/compiler.py", line 472, in _compile_core
ifr-trt-gpu0-1  |     pm.run(self.state)
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/core/compiler_machinery.py", line 364, in run
ifr-trt-gpu0-1  |     raise e
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/core/compiler_machinery.py", line 356, in run
ifr-trt-gpu0-1  |     self._runPass(idx, pass_inst, state)
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/core/compiler_lock.py", line 35, in _acquire_compile_lock
ifr-trt-gpu0-1  |     return func(*args, **kwargs)
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/core/compiler_machinery.py", line 311, in _runPass
ifr-trt-gpu0-1  |     mutated |= check(pss.run_pass, internal_state)
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/core/compiler_machinery.py", line 273, in check
ifr-trt-gpu0-1  |     mangled = func(compiler_state)
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/core/typed_passes.py", line 112, in run_pass
ifr-trt-gpu0-1  |     typemap, return_type, calltypes, errs = type_inference_stage(
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/core/typed_passes.py", line 93, in type_inference_stage
ifr-trt-gpu0-1  |     errs = infer.propagate(raise_errors=raise_errors)
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/core/typeinfer.py", line 1083, in propagate
ifr-trt-gpu0-1  |     errors = self.constraints.propagate(self)
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/core/typeinfer.py", line 182, in propagate
ifr-trt-gpu0-1  |     raise e
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/core/typeinfer.py", line 160, in propagate
ifr-trt-gpu0-1  |     constraint(typeinfer)
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/core/typeinfer.py", line 583, in __call__
ifr-trt-gpu0-1  |     self.resolve(typeinfer, typevars, fnty)
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/core/typeinfer.py", line 606, in resolve
ifr-trt-gpu0-1  |     sig = typeinfer.resolve_call(fnty, pos_args, kw_args)
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/core/typeinfer.py", line 1577, in resolve_call
ifr-trt-gpu0-1  |     return self.context.resolve_function_type(fnty, pos_args, kw_args)
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/core/typing/context.py", line 196, in resolve_function_type
ifr-trt-gpu0-1  |     res = self._resolve_user_function_type(func, args, kws)
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/core/typing/context.py", line 248, in _resolve_user_function_type
ifr-trt-gpu0-1  |     return func.get_call_type(self, args, kws)
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/core/types/functions.py", line 541, in get_call_type
ifr-trt-gpu0-1  |     self.dispatcher.get_call_template(args, kws)
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/core/dispatcher.py", line 318, in get_call_template
ifr-trt-gpu0-1  |     self.compile(tuple(args))
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/core/dispatcher.py", line 905, in compile
ifr-trt-gpu0-1  |     cres = self._compiler.compile(args, return_type)
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/core/dispatcher.py", line 80, in compile
ifr-trt-gpu0-1  |     status, retval = self._compile_cached(args, return_type)
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/core/dispatcher.py", line 94, in _compile_cached
ifr-trt-gpu0-1  |     retval = self._compile_core(args, return_type)
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/core/dispatcher.py", line 107, in _compile_core
ifr-trt-gpu0-1  |     cres = compiler.compile_extra(self.targetdescr.typing_context,
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/core/compiler.py", line 744, in compile_extra
ifr-trt-gpu0-1  |     return pipeline.compile_extra(func)
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/core/compiler.py", line 438, in compile_extra
ifr-trt-gpu0-1  |     return self._compile_bytecode()
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/core/compiler.py", line 506, in _compile_bytecode
ifr-trt-gpu0-1  |     return self._compile_core()
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/core/compiler.py", line 481, in _compile_core
ifr-trt-gpu0-1  |     raise e
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/core/compiler.py", line 472, in _compile_core
ifr-trt-gpu0-1  |     pm.run(self.state)
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/core/compiler_machinery.py", line 364, in run
ifr-trt-gpu0-1  |     raise e
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/core/compiler_machinery.py", line 356, in run
ifr-trt-gpu0-1  |     self._runPass(idx, pass_inst, state)
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/core/compiler_lock.py", line 35, in _acquire_compile_lock
ifr-trt-gpu0-1  |     return func(*args, **kwargs)
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/core/compiler_machinery.py", line 311, in _runPass
ifr-trt-gpu0-1  |     mutated |= check(pss.run_pass, internal_state)
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/core/compiler_machinery.py", line 273, in check
ifr-trt-gpu0-1  |     mangled = func(compiler_state)
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/core/typed_passes.py", line 112, in run_pass
ifr-trt-gpu0-1  |     typemap, return_type, calltypes, errs = type_inference_stage(
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/core/typed_passes.py", line 93, in type_inference_stage
ifr-trt-gpu0-1  |     errs = infer.propagate(raise_errors=raise_errors)
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/core/typeinfer.py", line 1083, in propagate
ifr-trt-gpu0-1  |     errors = self.constraints.propagate(self)
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/core/typeinfer.py", line 182, in propagate
ifr-trt-gpu0-1  |     raise e
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/core/typeinfer.py", line 160, in propagate
ifr-trt-gpu0-1  |     constraint(typeinfer)
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/core/typeinfer.py", line 583, in __call__
ifr-trt-gpu0-1  |     self.resolve(typeinfer, typevars, fnty)
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/core/typeinfer.py", line 606, in resolve
ifr-trt-gpu0-1  |     sig = typeinfer.resolve_call(fnty, pos_args, kw_args)
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/core/typeinfer.py", line 1577, in resolve_call
ifr-trt-gpu0-1  |     return self.context.resolve_function_type(fnty, pos_args, kw_args)
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/core/typing/context.py", line 196, in resolve_function_type
ifr-trt-gpu0-1  |     res = self._resolve_user_function_type(func, args, kws)
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/core/typing/context.py", line 248, in _resolve_user_function_type
ifr-trt-gpu0-1  |     return func.get_call_type(self, args, kws)
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/core/types/functions.py", line 541, in get_call_type
ifr-trt-gpu0-1  |     self.dispatcher.get_call_template(args, kws)
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/core/dispatcher.py", line 318, in get_call_template
ifr-trt-gpu0-1  |     self.compile(tuple(args))
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/core/dispatcher.py", line 912, in compile
ifr-trt-gpu0-1  |     self._cache.save_overload(sig, cres)
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/core/caching.py", line 652, in save_overload
ifr-trt-gpu0-1  |     self._save_overload(sig, data)
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/core/caching.py", line 662, in _save_overload
ifr-trt-gpu0-1  |     self._cache_file.save(key, data)
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/core/caching.py", line 478, in save
ifr-trt-gpu0-1  |     self._save_index(overloads)
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/core/caching.py", line 522, in _save_index
ifr-trt-gpu0-1  |     data = self._dump(data)
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/core/caching.py", line 550, in _dump
ifr-trt-gpu0-1  |     return dumps(obj)
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/core/serialize.py", line 58, in dumps
ifr-trt-gpu0-1  |     p.dump(obj)
ifr-trt-gpu0-1  |   File "/usr/local/lib/python3.10/dist-packages/numba/cloudpickle/cloudpickle.py", line 1262, in dump
ifr-trt-gpu0-1  |     return super().dump(obj)
ifr-trt-gpu0-1  | TypeError: cannot pickle 'generator' object
```

**Comment by SthPhoenix** [comment]
Hi! It seems like `numba` has some troubles compiling on your server CPU architecture. Is it some newer AMD CPU?

**Comment by barrycarey** [comment]
Thanks for the reply. I'll test out a few different versions.

The server is a VM and the base CPU is an EPYC 7502

**Comment by SthPhoenix** [comment]
Hm, that's interesting, 7502 is quite old CPU.

**Comment by barrycarey** [comment]
Yeah it's a bit old. Odd thing is my desktop is a 3900x so they're both Zen 2

**Comment by SthPhoenix** [comment]
Maybe some virtualization issues?

**Comment by barrycarey** [comment]
pinning Numba to 0.59.1 fixed the issue. 

Thank you for the response
