### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/models/onnx/retinaface_r50_v1/retinaface_r50_v1.onnx'``

### ISSUE THREAD

**Issue by nguyenvietquoc2569** [SthPhoenix/InsightFace-REST#17]
Hi Team, any chance you know how this one happen
I really appreciate that
Thank you so much   

    return future.result()
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/server.py", line 55, in serv
    config.load()

  File "/usr/local/lib/python3.8/dist-packages/uvicorn/config.py", line 308, in load

    self.loaded_app = import_from_string(self.app)

  File "/usr/local/lib/python3.8/dist-packages/uvicorn/importer.py", line 20, in import_from_string

    module = importlib.import_module(module_str)

  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module

    return _bootstrap._gcd_import(name[level:], package, level)

  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import

  File "<frozen importlib._bootstrap>", line 991, in _find_and_load

  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked

  File "<frozen importlib._bootstrap_external>", line 783, in exec_module

  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

  File "./app.py", line 34, in <module>

    processing = Processing(det_name=configs.models.det_name, rec_name=configs.models.rec_name,

  File "./modules/processing.py", line 121, in __init__

    self.model = FaceAnalysis(det_name=det_name, rec_name=rec_name, ga_name=ga_name, device=device,

  File "./modules/face_model.py", line 69, in __init__

    self.det_model = Detector(det_name=det_name, device=device, max_size=self.max_size,

  File "./modules/face_model.py", line 35, in __init__

    self.retina = get_model(det_name, backend_name=backend_name, force_fp16=force_fp16, im_size=max_size,

  File "./modules/model_zoo/getter.py", line 175, in get_model

    model_path = prepare_backend(model_name, backend_name, im_size=im_size, max_batch_size=max_batch_size, config=config, force_fp16=force_fp16,

  File "./modules/model_zoo/getter.py", line 115, in prepare_backend

    model = onnx.load(onnx_path)

  File "/usr/local/lib/python3.8/dist-packages/onnx/__init__.py", line 114, in load_model

    s = _load_bytes(f)

  File "/usr/local/lib/python3.8/dist-packages/onnx/__init__.py", line 30, in _load_bytes

    with open(cast(Text, f), 'rb') as readable:

FileNotFoundError: [Errno 2] No such file or directory: '/models/onnx/retinaface_r50_v1/retinaface_r50_v1.onnx'

Preparing models...

[22:14:46] INFO - Preparing 'arcface_r100_v1' model...

[22:14:46] INFO - Reshaping ONNX inputs to: (1, 3, 112, 112)

[22:14:46] INFO - Building TRT engine for arcface_r100_v1...

mxnet version: 1.7.0

onnx version: 1.7.0

Traceback (most recent call last):

  File "prepare_models.py", line 45, in <module>

    prepare_models()

  File "prepare_models.py", line 40, in prepare_models

    prepare_backend(model_name=model, backend_name=backend_name, im_size=max_size, force_fp16=force_fp16,

  File "/app/modules/model_zoo/getter.py", line 126, in prepare_backend

    convert_onnx(temp_onnx_model,

TypeError: 'NoneType' object is not callable

Starting InsightFace-REST using 1 workers.

[22:14:47] INFO - Reshaping ONNX inputs to: (1, 3, 640, 640)

mxnet version: 1.7.0

onnx version: 1.7.0

Traceback (most recent call last):

  File "/usr/local/bin/uvicorn", line 8, in <module>

    sys.exit(main())

  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 829, in __call__

    return self.main(*args, **kwargs)

  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 782, in main

    rv = self.invoke(ctx)

  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1066, in invoke

    return ctx.invoke(self.callback, **ctx.params)

  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 610, in invoke

    return callback(*args, **kwargs)

  File "/usr/local/lib/python3.8/dist-packages/uvicorn/main.py", line 362, in main

    run(**kwargs)

  File "/usr/local/lib/python3.8/dist-packages/uvicorn/main.py", line 386, in run

    server.run()

  File "/usr/local/lib/python3.8/dist-packages/uvicorn/server.py", line 48, in run

    loop.run_until_complete(self.serve(sockets=sockets))

  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete

    return future.result()

  File "/usr/local/lib/python3.8/dist-packages/uvicorn/server.py", line 55, in serve

    config.load()

  File "/usr/local/lib/python3.8/dist-packages/uvicorn/config.py", line 308, in load

    self.loaded_app = import_from_string(self.app)

  File "/usr/local/lib/python3.8/dist-packages/uvicorn/importer.py", line 20, in import_from_string

    module = importlib.import_module(module_str)

  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module

    return _bootstrap._gcd_import(name[level:], package, level)

  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import

  File "<frozen importlib._bootstrap>", line 991, in _find_and_load

  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked

  File "<frozen importlib._bootstrap_external>", line 783, in exec_module

  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

  File "./app.py", line 34, in <module>

    processing = Processing(det_name=configs.models.det_name, rec_name=configs.models.rec_name,

  File "./modules/processing.py", line 121, in __init__

    self.model = FaceAnalysis(det_name=det_name, rec_name=rec_name, ga_name=ga_name, device=device,

  File "./modules/face_model.py", line 69, in __init__

    self.det_model = Detector(det_name=det_name, device=device, max_size=self.max_size,

  File "./modules/face_model.py", line 35, in __init__

    self.retina = get_model(det_name, backend_name=backend_name, force_fp16=force_fp16, im_size=max_size,

  File "./modules/model_zoo/getter.py", line 175, in get_model

    model_path = prepare_backend(model_name, backend_name, im_size=im_size, max_batch_size=max_batch_size, config=config, force_fp16=force_fp16,

  File "./modules/model_zoo/getter.py", line 115, in prepare_backend

    model = onnx.load(onnx_path)

  File "/usr/local/lib/python3.8/dist-packages/onnx/__init__.py", line 114, in load_model

    s = _load_bytes(f)

  File "/usr/local/lib/python3.8/dist-packages/onnx/__init__.py", line 30, in _load_bytes

    with open(cast(Text, f), 'rb') as readable:

FileNotFoundError: [Errno 2] No such file or directory: '/models/onnx/retinaface_r50_v1/retinaface_r50_v1.onnx'``

**Comment by SthPhoenix** [comment]
Hi!
Could you please provide more info on your issue?
Are you getting this error when running docker container? Are you using provided `deploy_trt.sh` script to start container, as explained in readme?

**Comment by nguyenvietquoc2569** [comment]
Yes Sir, I start from scatch with deploy_trt.sh. I already have cuda 11 and nvidia-driver 450 installed.
I checkout master branch. 
----
Now i am able to run with branch v0.5.9. also manually downloaded mnet_cov2. 
is mnet_cov2 problem?

**Comment by SthPhoenix** [comment]
I've just checked master branch, it should work, but now it requires nvidia driver 455. 
Though it should not produce such error if it is a driver issue.

**Comment by SthPhoenix** [comment]
Building docker image again without cache indeed have led to this error. 
Closing this in favor of https://github.com/SthPhoenix/InsightFace-REST/issues/19, which contains solution.
