### ISSUE TITLE
cannot start container from  ./deploy_trt.sh

### ISSUE THREAD

**Issue by Asher-1** [SthPhoenix/InsightFace-REST#24]
ERROR: CUDA initialization failure with error 222. Please check your CUDA installation:  http://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html
mxnet version: 1.7.0
onnx version: 1.7.0
Traceback (most recent call last):
  File "prepare_models.py", line 45, in <module>
    prepare_models()
  File "prepare_models.py", line 40, in prepare_models
    prepare_backend(model_name=model, backend_name=backend_name, im_size=max_size, force_fp16=force_fp16,
  File "/app/modules/model_zoo/getter.py", line 127, in prepare_backend
    convert_onnx(temp_onnx_model,
  File "/app/modules/converters/onnx_to_trt.py", line 79, in convert_onnx
    engine = _build_engine_onnx(input_onnx=onnx_obj,
  File "/app/modules/converters/onnx_to_trt.py", line 25, in _build_engine_onnx
    with trt.Builder(TRT_LOGGER) as builder, \
TypeError: pybind11::init(): factory function returned nullptr
Starting InsightFace-REST using 1 workers.
[09:43:07] INFO - Reshaping ONNX inputs to: (1, 3, 640, 640)
mxnet version: 1.7.0
onnx version: 1.7.0

**Comment by SthPhoenix** [comment]
Hi, @Asher-1 ! Looks like you have older GPU drivers version,  ensure that you have 460.x.x  version drivers.

**Comment by Asher-1** [comment]
thank you, that works for me on 460.x.x

**Comment by SthPhoenix** [comment]
Closed as resolved.
