### ISSUE TITLE
Error while trying to hit /extract api on test image.

### ISSUE THREAD

**Issue by gaushh** [SthPhoenix/InsightFace-REST#36]
I am using deploy_cpu.sh to run a container on my local machine. The container is up and running. When I try using /extract endpoint on a test image using the example provided, I get a null response. 
# Request:
 ```
{
  "images": {
    "data": [
      "string"
    ],
    "urls": [
      "test_images/Stallone.jpg"
    ]
  },
  "max_size": [
    640,
    640
  ],
  "threshold": 0.6,
  "embed_only": false,
  "return_face_data": false,
  "return_landmarks": false,
  "extract_embedding": true,
  "extract_ga": true,
  "limit_faces": 0,
  "min_face_size": 0,
  "verbose_timings": true,
  "api_ver": "1"
}

```

# Error

```
Traceback (most recent call last):
  File "/app/./modules/processing.py", line 235, in embed
    faces = await self.model.get(image, max_size=max_size, threshold=threshold,
  File "/app/./modules/face_model.py", line 220, in get
    faces = [e for e in self.process_faces(faces, extract_embedding=extract_embedding,
  File "/app/./modules/face_model.py", line 220, in <listcomp>
    faces = [e for e in self.process_faces(faces, extract_embedding=extract_embedding,
  File "/app/./modules/face_model.py", line 138, in process_faces
    ga = self.ga_model.get(crops)
  File "/app/./modules/model_zoo/exec_backends/onnxrt_backend.py", line 51, in get
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
cv2.error: OpenCV(4.5.2) /tmp/pip-req-build-eirhwqtr/opencv/modules/imgproc/src/color.simd_helpers.hpp:92: error: (-2:Unspecified error) in function 'cv::impl::{anonymous}::CvtHelper<VScn, VDcn, VDepth, sizePolicy>::CvtHelper(cv::InputArray, cv::OutputArray, int) [with VScn = cv::impl::{anonymous}::Set<3, 4>; VDcn = cv::impl::{anonymous}::Set<3, 4>; VDepth = cv::impl::{anonymous}::Set<0, 2, 5>; cv::impl::{anonymous}::SizePolicy sizePolicy = cv::impl::<unnamed>::NONE; cv::InputArray = const cv::_InputArray&; cv::OutputArray = const cv::_OutputArray&]'
> Invalid number of channels in input image:
>     'VScn::contains(scn)'
> where
>     'scn' is 112
```

**Comment by SthPhoenix** [comment]
Should be fixed now
