### ISSUE TITLE
cpu multipart detection error

### ISSUE THREAD

**Issue by MyraBaba** [SthPhoenix/InsightFace-REST#63]
Hi,

I trying to run cpu docker on my mac os x. its deployed succesfully and I try to send lumia.jpd from api multipart it gives error : 

`docker attach 0d72e0e344fd
100%|██████████████████████████████████████████████████████████████████████████| 254556/254556 [03:27<00:00, 1228.47KB/s]
100%|██████████████████████████████████████████████████████████████████████████████| 3219/3219 [00:02<00:00, 1471.47KB/s]
Starting InsightFace-REST using 1 workers.
WARNING:root:No module named 'cupy'
(1, 3, 640, 640)
INFO:     Started server process [37]
INFO:uvicorn.error:Started server process [37]
INFO:     Waiting for application startup.
INFO:uvicorn.error:Waiting for application startup.
INFO:     Application startup complete.
INFO:uvicorn.error:Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:18080 (Press CTRL+C to quit)
INFO:uvicorn.error:Uvicorn running on http://0.0.0.0:18080 (Press CTRL+C to quit)
INFO:     127.0.0.1:54150 - "GET /info HTTP/1.1" 200 OK
INFO:     127.0.0.1:54152 - "GET /info HTTP/1.1" 200 OK
INFO:     172.17.0.1:38110 - "GET /docs HTTP/1.1" 200 OK
INFO:     172.17.0.1:38110 - "GET /static/swagger-ui.css HTTP/1.1" 200 OK
INFO:     172.17.0.1:38114 - "GET /static/swagger-ui-bundle.js HTTP/1.1" 200 OK
INFO:     172.17.0.1:38114 - "GET /openapi.json HTTP/1.1" 200 OK
INFO:     172.17.0.1:38110 - "GET /static/favicon.png HTTP/1.1" 304 Not Modified
INFO:     172.17.0.1:38118 - "POST /multipart/draw_detections HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 373, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 226, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 159, in run_endpoint_function
    return await dependant.call(**values)
  File "/app/./app.py", line 128, in draw_upl
    output = await processing.draw(file, threshold=threshold,
  File "/app/./modules/processing.py", line 223, in draw
    faces = await self.model.get([image], threshold=threshold, return_face_data=False,
  File "/app/./modules/face_model.py", line 211, in get
    det_predictions = zip(*_partial_detect(batch_imgs))
  File "/app/./modules/face_model.py", line 45, in detect
    bboxes, landmarks = self.retina.detect(data, threshold=threshold)
  File "/app/./modules/model_zoo/detectors/scrfd.py", line 217, in detect
    blob = self._preprocess(imgs)
  File "/app/./modules/model_zoo/detectors/scrfd.py", line 292, in _preprocess
    blob = cv2.dnn.blobFromImage(
cv2.error: OpenCV(4.5.4) /tmp/pip-req-build-24v3eisa/opencv/modules/dnn/src/dnn.cpp:370: error: (-215:Assertion failed) image0.dims == 2 in function 'blobFromImages'

ERROR:uvicorn.error:Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 373, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 226, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 159, in run_endpoint_function
    return await dependant.call(**values)
  File "/app/./app.py", line 128, in draw_upl
    output = await processing.draw(file, threshold=threshold,
  File "/app/./modules/processing.py", line 223, in draw
    faces = await self.model.get([image], threshold=threshold, return_face_data=False,
  File "/app/./modules/face_model.py", line 211, in get
    det_predictions = zip(*_partial_detect(batch_imgs))
  File "/app/./modules/face_model.py", line 45, in detect
    bboxes, landmarks = self.retina.detect(data, threshold=threshold)
  File "/app/./modules/model_zoo/detectors/scrfd.py", line 217, in detect
    blob = self._preprocess(imgs)
  File "/app/./modules/model_zoo/detectors/scrfd.py", line 292, in _preprocess
    blob = cv2.dnn.blobFromImage(
cv2.error: OpenCV(4.5.4) /tmp/pip-req-build-24v3eisa/opencv/modules/dnn/src/dnn.cpp:370: error: (-215:Assertion failed) image0.dims == 2 in function 'blobFromImages'

INFO:     127.0.0.1:54166 - "GET /info HTTP/1.1" 200 OK
<img width="1431" alt="Screen Shot 2021-12-29 at 12 56 04" src="https://user-images.githubusercontent.com/17505439/147650009-95283269-494f-42fc-8c0e-f851b4c7ff50.png">
`

**Comment by SthPhoenix** [comment]
I'm currently working on solution, for now closing as duplicate issue. See #62

**Comment by MyraBaba** [comment]
Thanks. 

Also if possible please ad instructions to run as and app without docker. 

Best

**Comment by SthPhoenix** [comment]
> Thanks.
> 
> Also if possible please ad instructions to run as and app without docker.
> 
> Best

You mean running without FastAPI as stand-alone module?
 In this case there are some issues in current version - module is using some asyncio features to optimize FastAPI performance, which make it incompatible with synchronous code.

**Comment by MyraBaba** [comment]
I mean to run from command line :  uvicorn app:app --port 18080 --host 0.0.0.0 --workers 4
 
So we can debug see what’s going on. Not from docker.

İt gives model error. Ie:

/models  folder can’t be created Mac OS X for security reason. So I changed to it to other place.

The errors:


‘
(InsightFace-REST-Nov2021) ➜ /Users/tulpar/Projects/InsightFace-REST/src/api_trt   git:(master) ✗ uvicorn app:app --port 18080 --host 0.0.0.0 --workers 4
INFO:     Uvicorn running on http://0.0.0.0:18080 (Press CTRL+C to quit)
INFO:     Started parent process [78200]
WARNING:root:No module named 'cupy'
WARNING:root:No module named 'cupy'
WARNING:root:No module named 'cupy'
WARNING:root:No module named 'cupy'
Process SpawnProcess-1:
Process SpawnProcess-4:
Process SpawnProcess-3:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/tulpar/Projects/Deepfake-Detection2/venv/InsightFace-REST-Nov2021/lib/python3.8/site-packages/uvicorn/subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/Users/tulpar/Projects/Deepfake-Detection2/venv/InsightFace-REST-Nov2021/lib/python3.8/site-packages/uvicorn/server.py", line 68, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/tulpar/Projects/Deepfake-Detection2/venv/InsightFace-REST-Nov2021/lib/python3.8/site-packages/uvicorn/server.py", line 76, in serve
    config.load()
  File "/Users/tulpar/Projects/Deepfake-Detection2/venv/InsightFace-REST-Nov2021/lib/python3.8/site-packages/uvicorn/config.py", line 456, in load
    self.loaded_app = import_from_string(self.app)
  File "/Users/tulpar/Projects/Deepfake-Detection2/venv/InsightFace-REST-Nov2021/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
Traceback (most recent call last):
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/tulpar/Projects/InsightFace-REST/src/api_trt/./app.py", line 36, in <module>
    processing = Processing(det_name=configs.models.det_name, rec_name=configs.models.rec_name,
  File "/Users/tulpar/Projects/InsightFace-REST/src/api_trt/./modules/processing.py", line 95, in __init__
    self.model = FaceAnalysis(det_name=det_name, rec_name=rec_name, ga_name=ga_name, device=device,
  File "/Users/tulpar/Projects/InsightFace-REST/src/api_trt/./modules/face_model.py", line 91, in __init__
    self.det_model = Detector(det_name=det_name, device=device, max_size=self.max_size,
  File "/Users/tulpar/Projects/InsightFace-REST/src/api_trt/./modules/face_model.py", line 38, in __init__
    self.retina = get_model(det_name, backend_name=backend_name, force_fp16=force_fp16, im_size=max_size,
  File "/Users/tulpar/Projects/InsightFace-REST/src/api_trt/./modules/model_zoo/getter.py", line 204, in get_model
    model_path = prepare_backend(model_name, backend_name, im_size=im_size, max_batch_size=max_batch_size,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
Traceback (most recent call last):
  File "/Users/tulpar/Projects/InsightFace-REST/src/api_trt/./modules/model_zoo/getter.py", line 147, in prepare_backend
    model = onnx.load(onnx_path)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/tulpar/Projects/Deepfake-Detection2/venv/InsightFace-REST-Nov2021/lib/python3.8/site-packages/onnx/__init__.py", line 120, in load_model
    s = _load_bytes(f)
  File "/Users/tulpar/Projects/Deepfake-Detection2/venv/InsightFace-REST-Nov2021/lib/python3.8/site-packages/uvicorn/subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/Users/tulpar/Projects/Deepfake-Detection2/venv/InsightFace-REST-Nov2021/lib/python3.8/site-packages/onnx/__init__.py", line 34, in _load_bytes
    with open(cast(Text, f), 'rb') as readable:
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
Process SpawnProcess-2:
  File "/Users/tulpar/Projects/Deepfake-Detection2/venv/InsightFace-REST-Nov2021/lib/python3.8/site-packages/uvicorn/server.py", line 68, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/tulpar/Projects/Deepfake-Detection2/venv/InsightFace-REST-Nov2021/lib/python3.8/site-packages/uvicorn/server.py", line 76, in serve
    config.load()
FileNotFoundError: [Errno 2] No such file or directory: '/Users/tulpar/models/onnx/retinaface_mnet025_v2/retinaface_mnet025_v2.onnx'
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/tulpar/Projects/Deepfake-Detection2/venv/InsightFace-REST-Nov2021/lib/python3.8/site-packages/uvicorn/config.py", line 456, in load
    self.loaded_app = import_from_string(self.app)
  File "/Users/tulpar/Projects/Deepfake-Detection2/venv/InsightFace-REST-Nov2021/lib/python3.8/site-packages/uvicorn/subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/Users/tulpar/Projects/Deepfake-Detection2/venv/InsightFace-REST-Nov2021/lib/python3.8/site-packages/uvicorn/server.py", line 68, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/Users/tulpar/Projects/Deepfake-Detection2/venv/InsightFace-REST-Nov2021/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/tulpar/Projects/InsightFace-REST/src/api_trt/./app.py", line 36, in <module>
    processing = Processing(det_name=configs.models.det_name, rec_name=configs.models.rec_name,
  File "/Users/tulpar/Projects/Deepfake-Detection2/venv/InsightFace-REST-Nov2021/lib/python3.8/site-packages/uvicorn/server.py", line 76, in serve
    config.load()
  File "/Users/tulpar/Projects/Deepfake-Detection2/venv/InsightFace-REST-Nov2021/lib/python3.8/site-packages/uvicorn/config.py", line 456, in load
    self.loaded_app = import_from_string(self.app)
  File "/Users/tulpar/Projects/Deepfake-Detection2/venv/InsightFace-REST-Nov2021/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/Users/tulpar/Projects/InsightFace-REST/src/api_trt/./modules/processing.py", line 95, in __init__
    self.model = FaceAnalysis(det_name=det_name, rec_name=rec_name, ga_name=ga_name, device=device,
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "/Users/tulpar/Projects/InsightFace-REST/src/api_trt/./modules/face_model.py", line 91, in __init__
    self.det_model = Detector(det_name=det_name, device=device, max_size=self.max_size,
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/tulpar/Projects/InsightFace-REST/src/api_trt/./app.py", line 36, in <module>
    processing = Processing(det_name=configs.models.det_name, rec_name=c  File "/Users/tulpar/Projects/InsightFace-REST/src/api_trt/./modules/face_model.py", line 38, in __init__
    self.retina = get_model(det_name, backend_name=backend_name, force_fp16=force_fp16, im_size=max_size,
onfigs.models.rec_name,
  File "/Users/tulpar/Projects/InsightFace-REST/src/api_trt/./modules/processing.py", line 95, in __init__
    self.model = FaceAnalysis(det_name=det_name, rec_name=rec_name, ga_name=ga_name, device=device,
  File "/Users/tulpar/Projects/InsightFace-REST/src/api_trt/./modules/face_model.py", line 91, in __init__
    self.det_model = Detector(det_name=det_name, device=device, max_size=self.max_size,
  File "/Users/tulpar/Projects/InsightFace-REST/src/api_trt/./modules/model_zoo/getter.py", line 204, in get_model
    model_path = prepare_backend(model_name, backend_name, im_size=im_size, max_batch_size=max_batch_size,
  File "/Users/tulpar/Projects/InsightFace-REST/src/api_trt/./modules/face_model.py", line 38, in __init__
    self.retina = get_model(det_name, backend_name=backend_name, force_fp16=force_fp16, im_size=max_size,
  File "/Users/tulpar/Projects/InsightFace-REST/src/api_trt/./modules/model_zoo/getter.py", line 147, in prepare_backend
    model = onnx.load(onnx_path)
  File "/Users/tulpar/Projects/InsightFace-REST/src/api_trt/./modules/model_zoo/getter.py", line 204, in get_model
    model_path = prepare_backend(model_name, backend_name, im_size=im_size, max_batch_size=max_batch_size,
  File "/Users/tulpar/Projects/Deepfake-Detection2/venv/InsightFace-REST-Nov2021/lib/python3.8/site-packages/onnx/__init__.py", line 120, in load_model
    s = _load_bytes(f)
  File "/Users/tulpar/Projects/InsightFace-REST/src/api_trt/./modules/model_zoo/getter.py", line 147, in prepare_backend
    model = onnx.load(onnx_path)
  File "/Users/tulpar/Projects/Deepfake-Detection2/venv/InsightFace-REST-Nov2021/lib/python3.8/site-packages/onnx/__init__.py", line 34, in _load_bytes
    with open(cast(Text, f), 'rb') as readable:
  File "/Users/tulpar/Projects/Deepfake-Detection2/venv/InsightFace-REST-Nov2021/lib/python3.8/site-packages/onnx/__init__.py", line 120, in load_model
    s = _load_bytes(f)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/tulpar/models/onnx/retinaface_mnet025_v2/retinaface_mnet025_v2.onnx'
  File "/Users/tulpar/Projects/Deepfake-Detection2/venv/InsightFace-REST-Nov2021/lib/python3.8/site-packages/onnx/__init__.py", line 34, in _load_bytes
    with open(cast(Text, f), 'rb') as readable:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/tulpar/models/onnx/retinaface_mnet025_v2/retinaface_mnet025_v2.onnx'
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/tulpar/Projects/Deepfake-Detection2/venv/InsightFace-REST-Nov2021/lib/python3.8/site-packages/uvicorn/subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/Users/tulpar/Projects/Deepfake-Detection2/venv/InsightFace-REST-Nov2021/lib/python3.8/site-packages/uvicorn/server.py", line 68, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/tulpar/Projects/Deepfake-Detection2/venv/InsightFace-REST-Nov2021/lib/python3.8/site-packages/uvicorn/server.py", line 76, in serve
    config.load()
  File "/Users/tulpar/Projects/Deepfake-Detection2/venv/InsightFace-REST-Nov2021/lib/python3.8/site-packages/uvicorn/config.py", line 456, in load
    self.loaded_app = import_from_string(self.app)
  File "/Users/tulpar/Projects/Deepfake-Detection2/venv/InsightFace-REST-Nov2021/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/tulpar/Projects/InsightFace-REST/src/api_trt/./app.py", line 36, in <module>
    processing = Processing(det_name=configs.models.det_name, rec_name=configs.models.rec_name,
  File "/Users/tulpar/Projects/InsightFace-REST/src/api_trt/./modules/processing.py", line 95, in __init__
    self.model = FaceAnalysis(det_name=det_name, rec_name=rec_name, ga_name=ga_name, device=device,
  File "/Users/tulpar/Projects/InsightFace-REST/src/api_trt/./modules/face_model.py", line 91, in __init__
    self.det_model = Detector(det_name=det_name, device=device, max_size=self.max_size,
  File "/Users/tulpar/Projects/InsightFace-REST/src/api_trt/./modules/face_model.py", line 38, in __init__
    self.retina = get_model(det_name, backend_name=backend_name, force_fp16=force_fp16, im_size=max_size,
  File "/Users/tulpar/Projects/InsightFace-REST/src/api_trt/./modules/model_zoo/getter.py", line 204, in get_model
    model_path = prepare_backend(model_name, backend_name, im_size=im_size, max_batch_size=max_batch_size,
  File "/Users/tulpar/Projects/InsightFace-REST/src/api_trt/./modules/model_zoo/getter.py", line 147, in prepare_backend
    model = onnx.load(onnx_path)
  File "/Users/tulpar/Projects/Deepfake-Detection2/venv/InsightFace-REST-Nov2021/lib/python3.8/site-packages/onnx/__init__.py", line 120, in load_model
    s = _load_bytes(f)
  File "/Users/tulpar/Projects/Deepfake-Detection2/venv/InsightFace-REST-Nov2021/lib/python3.8/site-packages/onnx/__init__.py", line 34, in _load_bytes
    with open(cast(Text, f), 'rb') as readable:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/tulpar/models/onnx/retinaface_mnet025_v2/retinaface_mnet025_v2.onnx'


'

**Comment by SthPhoenix** [comment]
Models dir location is currently read from `MODELS_DIR` environment variable. You can launch app like:
```
export MODELS_DIR=path/to/your/models
uvicorn app:app --port 18080 --host 0.0.0.0 --workers 4
```

You can set any environment variables used to run docker image this way, for example `'INFERENCE_BACKEND'=onnx`, `DET_NAME=scrfd_500m_gnkps` and `REC_NAME=w600k_r50` 

I'll add it as argument to related classes though.

**Comment by SthPhoenix** [comment]
I have added `root_dir` argument to Processing class. You can override it by changing its value in `app.py`.
Keep in mind that environment variables have higher priority in this project and their value will be used first instead of hard-coded values

**Comment by MyraBaba** [comment]
Still error :




(InsightFace-REST-Nov2021) ➜ /Users/tulpar/Projects/InsightFace-REST/src/api_trt   uvicorn app:app --port 18080 --host 0.0.0.0 --workers 4
INFO:     Uvicorn running on http://0.0.0.0:18080 (Press CTRL+C to quit)
INFO:     Started parent process [79026]
Traceback (most recent call last):
  File "<frozen importlib._bootstrap_external>", line 1346, in _path_importer_cache
KeyError: '.'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tulpar/Projects/Deepfake-Detection2/venv/InsightFace-REST-Nov2021/bin/uvicorn", line 8, in <module>
    sys.exit(main())
  File "/Users/tulpar/Projects/Deepfake-Detection2/venv/InsightFace-REST-Nov2021/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/tulpar/Projects/Deepfake-Detection2/venv/InsightFace-REST-Nov2021/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/tulpar/Projects/Deepfake-Detection2/venv/InsightFace-REST-Nov2021/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/tulpar/Projects/Deepfake-Detection2/venv/InsightFace-REST-Nov2021/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/tulpar/Projects/Deepfake-Detection2/venv/InsightFace-REST-Nov2021/lib/python3.8/site-packages/uvicorn/main.py", line 426, in main
    run(app, **kwargs)
  File "/Users/tulpar/Projects/Deepfake-Detection2/venv/InsightFace-REST-Nov2021/lib/python3.8/site-packages/uvicorn/main.py", line 450, in run
    Multiprocess(config, target=server.run, sockets=[sock]).run()
  File "/Users/tulpar/Projects/Deepfake-Detection2/venv/InsightFace-REST-Nov2021/lib/python3.8/site-packages/uvicorn/supervisors/multiprocess.py", line 44, in run
    self.startup()
  File "/Users/tulpar/Projects/Deepfake-Detection2/venv/InsightFace-REST-Nov2021/lib/python3.8/site-packages/uvicorn/supervisors/multiprocess.py", line 62, in startup
    process.start()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/context.py", line 283, in _Popen
    from .popen_spawn_posix import Popen
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 6, in <module>
    from . import spawn
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 13, in <module>
    import runpy
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 914, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1407, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1376, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1348, in _path_importer_cache
  File "<frozen importlib._bootstrap_external>", line 1324, in _path_hooks
  File "<frozen importlib._bootstrap_external>", line 1594, in path_hook_for_FileFinder
  File "<frozen importlib._bootstrap_external>", line 1470, in __init__
FileNotFoundError: [Errno 2] No such file or directory

**Comment by SthPhoenix** [comment]
On Ubuntu I was able to run CPU version without docker with following modifications to `src/api_trt/entrypoint.sh`:
```
#!/bin/bash

echo Preparing models...
python prepare_models.py

echo Starting InsightFace-REST using $NUM_WORKERS workers.
export MODELS_DIR=/home/user/PycharmProjects/InsightFace-REST/models
export INFERENCE_BACKEND=onnx
export NUM_WORKERS=1
uvicorn app:app --port 18080 --host 0.0.0.0 --workers $NUM_WORKERS
```
