### ISSUE TITLE
Prepare models fails in a new container build because of AttributeError in helpers.py

### ISSUE THREAD

**Issue by felixdollack** [SthPhoenix/InsightFace-REST#80]
```
Traceback (most recent call last):
|   File "prepare_models.py", line 52, in <module>
|     prepare_models()
|   File "prepare_models.py", line 20, in prepare_models
|     env_configs = EnvConfigs()
|   File "/app/env_parser.py", line 45, in __init__
|     self.models = Models()
|   File "/app/env_parser.py", line 33, in __init__
|     self.mask_detector = toNone(os.getenv("MASK_DETECTOR", None))
|   File "/app/modules/utils/helpers.py", line 22, in toNone
|     if input.lower() in ['', 'none', 'null']:
| AttributeError: 'NoneType' object has no attribute 'lower'
```

**Comment by SthPhoenix** [comment]
Thanks for help! Merged!
